// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HEMSystems.Entities.KhoaHLD.Models;

public partial class DevelopmentPlatformsKhoaHld
{
    public int PlatformKhoahldId { get; set; }

    public string PlatformName { get; set; }

    public string PlatformDescription { get; set; }

    public string WebsiteUrl { get; set; }

    public string CreatedBy { get; set; }

    public string SupportEmail { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<ProjectSubmissionsKhoaHld> ProjectSubmissionsKhoaHlds { get; set; } = new List<ProjectSubmissionsKhoaHld>();
}