// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HEMSystems.Entities.KhoaHLD.Models;

public partial class ProjectSubmissionsKhoaHld
{
    public int SubmissionKhoahldId { get; set; }

    public string TeamId { get; set; }

    public string RoundId { get; set; }

    public int? PlatformKhoahldId { get; set; }

    public string ProjectName { get; set; }

    public string ProjectDescription { get; set; }

    public string RepositoryUrl { get; set; }

    public string DemoUrl { get; set; }

    public string DocumentUrl { get; set; }

    public decimal? RepositorySizeMb { get; set; }

    public int? VersionNumber { get; set; }

    public string SubmittedBy { get; set; }

    public string SubmissionStatus { get; set; }

    public bool? IsDeployed { get; set; }

    public bool? IsLateSubmission { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual DevelopmentPlatformsKhoaHld PlatformKhoahld { get; set; }
}