// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using HEMSystems.Entities.KhoaHLD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace  HEMSystems.Repositories.KhoaHLD.DBContext
{


    public partial class HackathonManagementSystemContext : DbContext
    {
        public HackathonManagementSystemContext()
        {
        }

        public HackathonManagementSystemContext(DbContextOptions<HackathonManagementSystemContext> options)
            : base(options)
        {
        }

        public virtual DbSet<DevelopmentPlatformsKhoaHld> DevelopmentPlatformsKhoaHlds { get; set; }

        public virtual DbSet<ProjectSubmissionsKhoaHld> ProjectSubmissionsKhoaHlds { get; set; }

        public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

        public static string GetConnectionString(string connectionStringName)
        {
            var config = new ConfigurationBuilder()
                .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                .AddJsonFile("appsettings.json")
                .Build();

            string connectionString = config.GetConnectionString(connectionStringName);
            return connectionString;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
        //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        //        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-I5207PI\\SQLEXPRESS;Initial Catalog=HackathonManagementSystem;Persist Security Info=True;User ID=sa;Password=12345;Encrypt=False");

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DevelopmentPlatformsKhoaHld>(entity =>
            {
                entity.HasKey(e => e.PlatformKhoahldId).HasName("PK__Developm__3DC7B31C19E67D8A");

                entity.ToTable("DevelopmentPlatformsKhoaHLD");

                entity.Property(e => e.PlatformKhoahldId).HasColumnName("platform_Khoahld_id");
                entity.Property(e => e.CreatedAt)
                    .HasDefaultValueSql("(getdate())")
                    .HasColumnType("datetime")
                    .HasColumnName("created_at");
                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(255)
                    .HasColumnName("created_by");
                entity.Property(e => e.IsActive)
                    .HasDefaultValue(true)
                    .HasColumnName("is_active");
                entity.Property(e => e.PlatformDescription).HasColumnName("platform_description");
                entity.Property(e => e.PlatformName)
                    .HasMaxLength(255)
                    .HasColumnName("platform_name");
                entity.Property(e => e.SupportEmail)
                    .HasMaxLength(255)
                    .HasColumnName("support_email");
                entity.Property(e => e.UpdatedAt)
                    .HasColumnType("datetime")
                    .HasColumnName("updated_at");
                entity.Property(e => e.WebsiteUrl)
                    .HasMaxLength(500)
                    .HasColumnName("website_url");
            });

            modelBuilder.Entity<ProjectSubmissionsKhoaHld>(entity =>
            {
                entity.HasKey(e => e.SubmissionKhoahldId).HasName("PK__ProjectS__21B7B67C0E487419");

                entity.ToTable("ProjectSubmissionsKhoaHLD");

                entity.Property(e => e.SubmissionKhoahldId).HasColumnName("submission_Khoahld_id");
                entity.Property(e => e.DemoUrl)
                    .HasMaxLength(500)
                    .HasColumnName("demo_url");
                entity.Property(e => e.DocumentUrl)
                    .HasMaxLength(500)
                    .HasColumnName("document_url");
                entity.Property(e => e.IsDeployed)
                    .HasDefaultValue(false)
                    .HasColumnName("is_deployed");
                entity.Property(e => e.IsLateSubmission)
                    .HasDefaultValue(false)
                    .HasColumnName("is_late_submission");
                entity.Property(e => e.PlatformKhoahldId).HasColumnName("platform_Khoahld_id");
                entity.Property(e => e.ProjectDescription).HasColumnName("project_description");
                entity.Property(e => e.ProjectName)
                    .HasMaxLength(255)
                    .HasColumnName("project_name");
                entity.Property(e => e.RepositorySizeMb)
                    .HasColumnType("decimal(10, 2)")
                    .HasColumnName("repository_size_mb");
                entity.Property(e => e.RepositoryUrl)
                    .HasMaxLength(500)
                    .HasColumnName("repository_url");
                entity.Property(e => e.RoundId)
                    .HasMaxLength(255)
                    .HasColumnName("round_id");
                entity.Property(e => e.SubmissionStatus)
                    .HasMaxLength(100)
                    .HasColumnName("submission_status");
                entity.Property(e => e.SubmittedAt)
                    .HasColumnType("datetime")
                    .HasColumnName("submitted_at");
                entity.Property(e => e.SubmittedBy)
                    .HasMaxLength(255)
                    .HasColumnName("submitted_by");
                entity.Property(e => e.TeamId)
                    .HasMaxLength(255)
                    .HasColumnName("team_id");
                entity.Property(e => e.UpdatedAt)
                    .HasColumnType("datetime")
                    .HasColumnName("updated_at");
                entity.Property(e => e.VersionNumber)
                    .HasDefaultValue(1)
                    .HasColumnName("version_number");

                entity.HasOne(d => d.PlatformKhoahld).WithMany(p => p.ProjectSubmissionsKhoaHlds)
                    .HasForeignKey(d => d.PlatformKhoahldId)
                    .HasConstraintName("FK_ProjectSubmissionsKhoaHLD_DevelopmentPlatformsKhoaHLD");
            });

            modelBuilder.Entity<SystemUserAccount>(entity =>
            {
                entity.HasKey(e => e.UserAccountId);

                entity.ToTable("System.UserAccount");

                entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
                entity.Property(e => e.ApplicationCode).HasMaxLength(50);
                entity.Property(e => e.CreatedBy).HasMaxLength(50);
                entity.Property(e => e.CreatedDate).HasColumnType("datetime");
                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(150);
                entity.Property(e => e.EmployeeCode)
                    .IsRequired()
                    .HasMaxLength(50);
                entity.Property(e => e.FullName)
                    .IsRequired()
                    .HasMaxLength(100);
                entity.Property(e => e.ModifiedBy).HasMaxLength(50);
                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(100);
                entity.Property(e => e.Phone)
                    .IsRequired()
                    .HasMaxLength(50);
                entity.Property(e => e.RequestCode).HasMaxLength(50);
                entity.Property(e => e.UserName)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}